[env]
ELF = "stm32g0-rust"
DEBUG = "./target/thumbv6m-none-eabi/debug"
RELEASE = "./target/thumbv6m-none-eabi/release"
DEVICE = "STM32G031J6"
IF = "SWD"
SPEED = "2000"

[tasks.debug]
dependencies = ["build"]
script = [
'''
    JLinkGDBServer -device ${DEVICE} -if ${IF} -speed ${SPEED} > /dev/null &
    PID=$!
    script -q /dev/null -c \
        "arm-none-eabi-gdb ${DEBUG}/${ELF} \
            -ex 'set print asm-demangle on' \
            -ex 'target extended-remote :2331' \
            -ex 'monitor semihosting enable' \
            -ex 'monitor semihosting IOClient 3' \
            -ex 'monitor reset' \
            -ex 'load'"
    kill -2 $PID
'''
]

[tasks.bin]
dependencies = ["build-release"]
command = "arm-none-eabi-objcopy"
args = ["${RELEASE}/${ELF}", "-O", "binary", "${RELEASE}/${ELF}.bin"]

[tasks.flash]
dependencies = ["bin"]
script = [
'''
    JLinkExe -device ${DEVICE} -if ${IF} -speed ${SPEED} << EOF
        halt
        loadfile ${RELEASE}/${ELF}.bin 0
        r
        go
        exit
    EOF
'''
]
